import argparse
import json
import os
from collections import Counter
from typing import Iterable, Set, Tuple

import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


def load_graph(path: str) -> nx.Graph:
    ext = os.path.splitext(path)[1].lower()
    if ext == ".graphml":
        return nx.read_graphml(path)
    if ext == ".gexf":
        return nx.read_gexf(path)
    raise ValueError(f"Unsupported graph format: {ext}. Use .graphml or .gexf")


def node_text(node_id: str, attrs: dict) -> str:
    parts = [
        str(node_id),
        str(attrs.get("name", "")),
        str(attrs.get("label", "")),
        str(attrs.get("type", "")),
        str(attrs.get("description", "")),
        str(attrs.get("text", "")),
    ]
    return " ".join(parts).lower()


def find_seed_nodes(g: nx.Graph, queries: Iterable[str]) -> Set[str]:
    q = [x.strip().lower() for x in queries if x.strip()]
    seeds = set()
    if not q:
        return seeds
    for n, a in g.nodes(data=True):
        t = node_text(n, a)
        if any(query in t for query in q):
            seeds.add(n)
    return seeds


def multi_ego_subgraph(g: nx.Graph, seeds: Set[str], hops: int) -> nx.Graph:
    if not seeds:
        return g.copy()
    keep = set()
    und = g.to_undirected()
    for s in seeds:
        keep.update(nx.single_source_shortest_path_length(und, s, cutoff=hops).keys())
    return g.subgraph(keep).copy()


def trim_max_nodes(g: nx.Graph, max_nodes: int) -> nx.Graph:
    if g.number_of_nodes() <= max_nodes:
        return g
    # keep highest-degree nodes for readability
    ranked = sorted(g.degree, key=lambda x: x[1], reverse=True)
    keep = {n for n, _ in ranked[:max_nodes]}
    return g.subgraph(keep).copy()


def classify_node(attrs: dict, node_id: str) -> str:
    t = str(attrs.get("type", "")).lower()
    nid = str(node_id).lower()
    if "rtl" in t or nid.startswith("rtl_"):
        return "rtl"
    if "signal" in t or "port" in t or "register" in t or "spec" in t:
        return "spec"
    return "other"


def classify_edge(attrs: dict) -> str:
    t = str(attrs.get("type", attrs.get("relationship", ""))).lower()
    if "corresponds_to" in t:
        return "alignment"
    if "rtl" in t:
        return "rtl_struct"
    if "spec" in t:
        return "spec_rel"
    return "other"


def is_rtl_node(attrs: dict, node_id: str) -> bool:
    src = str(attrs.get("source", "")).strip().lower()
    typ = str(attrs.get("type", "")).strip().lower()
    nid = str(node_id).lower()
    name = str(attrs.get("name", attrs.get("label", ""))).lower()
    return (
        src == "rtl"
        or "rtl" in typ
        or nid.startswith("rtl_")
        or name.startswith("rtl_")
    )

def is_corresponds_edge(attrs: dict) -> bool:
    rel = str(attrs.get("relationship", "")).lower()
    typ = str(attrs.get("type", "")).lower()
    return "corresponds_to" in rel or "corresponds_to" in typ


def relation_label(attrs: dict) -> str:
    rel = attrs.get("relationship")
    typ = attrs.get("type")
    if rel is not None and str(rel).strip():
        return str(rel)
    if typ is not None and str(typ).strip():
        return str(typ)

    desc = str(attrs.get("description", "")).strip().strip('"')
    if not desc:
        return ""

    desc_l = desc.lower()
    relation_patterns = [
        (" is generated by ", "generated_by"),
        (" is used to ", "used_to"),
        (" is used for ", "used_for"),
        (" is a part of ", "part_of"),
        (" operates on ", "operates_on"),
        (" determines whether ", "determines"),
        (" contains ", "contains"),
        (" uses ", "uses"),
        (" clears ", "clears"),
        (" is divided by ", "divided_by"),
        (" has ", "has"),
    ]
    for needle, label in relation_patterns:
        if needle in desc_l:
            return label

    # Fallback: short readable snippet instead of generic "edge"
    compact = " ".join(desc.split())
    return compact[:32] + ("..." if len(compact) > 32 else "")


def choose_layout(
    g: nx.Graph,
    layout: str,
    graphviz_prog: str,
    seed: int,
) -> Tuple[dict, str]:
    """
    Returns (positions, layout_name_used)
    """
    if layout == "graphviz":
        try:
            from networkx.drawing.nx_agraph import graphviz_layout

            return graphviz_layout(g, prog=graphviz_prog), f"graphviz:{graphviz_prog}"
        except Exception:
            # Fallback to spring if pygraphviz/graphviz is unavailable
            n = max(g.number_of_nodes(), 1)
            spacing = max(0.06, min(0.55, 5.2 / (n**0.5)))
            return (
                nx.spring_layout(g, seed=seed, k=spacing, iterations=400),
                "spring(fallback)",
            )

    if layout == "kamada":
        return nx.kamada_kawai_layout(g), "kamada"

    # spring default
    n = max(g.number_of_nodes(), 1)
    spacing = max(0.06, min(0.55, 5.2 / (n**0.5)))
    return nx.spring_layout(g, seed=seed, k=spacing, iterations=400), "spring"


def draw_graph(
    g: nx.Graph,
    title: str,
    out_png: str,
    out_svg: str,
    out_pdf: str,
    fig_width: float,
    fig_height: float,
    node_label_font_size: int,
    edge_label_font_size: int,
    dpi: int,
    layout: str,
    graphviz_prog: str,
    seed: int,
    show_node_type_in_label: bool,
    edge_alpha: float,
    edge_width_scale: float,
    rtl_spec_corresponds_view: bool,
):
    draw_g = g
    if rtl_spec_corresponds_view:
        corresponds_edges = [
            (u, v, a)
            for u, v, a in g.edges(data=True)
            if is_corresponds_edge(a)
        ]
        if corresponds_edges:
            nodes_in_edges = set()
            for u, v, _ in corresponds_edges:
                nodes_in_edges.add(u)
                nodes_in_edges.add(v)
            draw_g = g.subgraph(nodes_in_edges).copy()
            draw_g.remove_edges_from(list(draw_g.edges()))
            for u, v, a in corresponds_edges:
                if u in draw_g and v in draw_g:
                    draw_g.add_edge(u, v, **a)
        else:
            # No corresponds edges present; keep original nodes but draw no edges.
            draw_g = g.copy()
            draw_g.remove_edges_from(list(draw_g.edges()))

    plt.figure(figsize=(fig_width, fig_height))
    pos, layout_used = choose_layout(draw_g, layout=layout, graphviz_prog=graphviz_prog, seed=seed)

    node_colors = []
    node_sizes = []
    labels = {}

    for n, a in draw_g.nodes(data=True):
        cls = classify_node(a, n)
        if rtl_spec_corresponds_view:
            if is_rtl_node(a, n):
                node_colors.append("#000000")  # RTL black
            else:
                node_colors.append("#D62728")  # Spec red
        else:
            if cls == "rtl":
                node_colors.append("#4C78A8")   # blue
            elif cls == "spec":
                node_colors.append("#9E9E9E")   # gray
            else:
                node_colors.append("#72B7B2")   # teal
        node_sizes.append(220 if cls != "other" else 170)

        name = str(a.get("name", a.get("label", n)))
        node_type = str(a.get("type", "")).strip()
        if node_type:
            labels[n] = f"{name}\n[{node_type}]"
        else:
            labels[n] = name

    edge_colors = []
    edge_widths = []
    for _, _, a in draw_g.edges(data=True):
        if rtl_spec_corresponds_view:
            edge_colors.append("#1F77B4")  # corresponds blue
            edge_widths.append(2.2 * edge_width_scale)
        else:
            cls = classify_edge(a)
            if cls == "alignment":
                edge_colors.append("#E45756")   # red
                edge_widths.append(2.0 * edge_width_scale)
            elif cls == "rtl_struct":
                edge_colors.append("#4C78A8")
                edge_widths.append(1.25 * edge_width_scale)
            elif cls == "spec_rel":
                edge_colors.append("#9E9E9E")
                edge_widths.append(1.1 * edge_width_scale)
            else:
                edge_colors.append("#BDBDBD")
                edge_widths.append(0.9 * edge_width_scale)

    nx.draw_networkx_edges(
        draw_g,
        pos,
        edge_color=edge_colors,
        width=edge_widths,
        alpha=edge_alpha,
    )
    nx.draw_networkx_nodes(draw_g, pos, node_color=node_colors, node_size=node_sizes, alpha=0.95)
    if show_node_type_in_label:
        rendered_labels = labels
    else:
        rendered_labels = {
            n: str(draw_g.nodes[n].get("name", draw_g.nodes[n].get("label", n))) for n in draw_g.nodes()
        }

    nx.draw_networkx_labels(
        draw_g,
        pos,
        labels=rendered_labels,
        font_size=node_label_font_size,
        bbox={"boxstyle": "round,pad=0.10", "fc": "white", "ec": "none", "alpha": 0.7},
    )

    edge_labels = {
        (u, v): lbl
        for u, v, a in draw_g.edges(data=True)
        for lbl in [relation_label(a)]
        if lbl and (not rtl_spec_corresponds_view or is_corresponds_edge(a))
    }
    nx.draw_networkx_edge_labels(
        draw_g,
        pos,
        edge_labels=edge_labels,
        font_size=edge_label_font_size,
        font_color="#111111",
        font_weight="bold",
        rotate=False,
        label_pos=0.5,
        bbox={"boxstyle": "round,pad=0.16", "fc": "white", "ec": "#444444", "alpha": 0.92},
    )

    if rtl_spec_corresponds_view:
        legend_items = [
            Line2D([0], [0], marker="o", color="w", label="RTL node", markerfacecolor="#000000", markersize=10),
            Line2D([0], [0], marker="o", color="w", label="Spec node", markerfacecolor="#D62728", markersize=10),
            Line2D([0], [0], color="#1F77B4", lw=2.2, label="corresponds_to edge"),
        ]
        legend_cols = 3
    else:
        legend_items = [
            Line2D([0], [0], marker="o", color="w", label="RTL node", markerfacecolor="#4C78A8", markersize=10),
            Line2D([0], [0], marker="o", color="w", label="Spec/semantic node", markerfacecolor="#9E9E9E", markersize=10),
            Line2D([0], [0], marker="o", color="w", label="Other node", markerfacecolor="#72B7B2", markersize=10),
            Line2D([0], [0], color="#E45756", lw=2.2, label="Alignment edge (corresponds_to)"),
            Line2D([0], [0], color="#4C78A8", lw=1.4, label="RTL structural edge"),
            Line2D([0], [0], color="#9E9E9E", lw=1.3, label="Spec relationship edge"),
        ]
        legend_cols = 3
    plt.legend(
        handles=legend_items,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.02),
        ncol=legend_cols,
        frameon=True,
        fontsize=max(8, node_label_font_size),
    )

    plt.title(f"{title}\nLayout: {layout_used} | Nodes: {draw_g.number_of_nodes()} | Edges: {draw_g.number_of_edges()}")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_png, dpi=dpi, bbox_inches="tight")
    plt.savefig(out_svg, bbox_inches="tight")
    plt.savefig(out_pdf, bbox_inches="tight")
    plt.close()


def graph_stats(g: nx.Graph) -> dict:
    e_types = Counter(classify_edge(a) for _, _, a in g.edges(data=True))
    n_types = Counter(classify_node(a, n) for n, a in g.nodes(data=True))
    return {
        "nodes": g.number_of_nodes(),
        "edges": g.number_of_edges(),
        "node_type_counts": dict(n_types),
        "edge_type_counts": dict(e_types),
    }


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def main():
    parser = argparse.ArgumentParser(description="Create publication-ready KG visualizations.")
    parser.add_argument("--graph", required=True, help="Path to fused graph (.graphml/.gexf)")
    parser.add_argument("--outdir", required=True, help="Output directory for figures/exports")
    parser.add_argument("--title", default="Unified KG (Spec + RTL + Signal Alignment)")
    parser.add_argument("--signals", default="", help="Comma-separated seed signal queries (e.g., nRST,WE_N,IRQ_OUT)")
    parser.add_argument("--hops", type=int, default=2, help="Neighborhood hops around seed nodes")
    parser.add_argument("--max-nodes", type=int, default=180, help="Cap nodes for readable figure")
    parser.add_argument("--full-graph", action="store_true", help="Render the full graph without seed/hop filtering or max-node trimming")
    parser.add_argument("--fig-width", type=float, default=32.0, help="Figure width in inches")
    parser.add_argument("--fig-height", type=float, default=22.0, help="Figure height in inches")
    parser.add_argument("--node-label-font-size", type=int, default=5, help="Font size for node labels")
    parser.add_argument("--edge-label-font-size", type=int, default=6, help="Font size for edge labels")
    parser.add_argument("--dpi", type=int, default=500, help="DPI for PNG export")
    parser.add_argument("--layout", choices=["graphviz", "spring", "kamada"], default="graphviz", help="Layout algorithm")
    parser.add_argument("--graphviz-prog", default="sfdp", help="Graphviz engine when --layout graphviz (e.g., sfdp, neato, dot)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for layout fallbacks")
    parser.add_argument("--edge-alpha", type=float, default=0.72, help="Edge transparency")
    parser.add_argument("--edge-width-scale", type=float, default=1.2, help="Global multiplier for edge widths")
    parser.add_argument("--hide-node-type-in-label", action="store_true", help="Hide [type] suffix in node labels to reduce clutter")
    parser.add_argument("--rtl-spec-corresponds-view", action="store_true", help="Render RTL nodes in black, spec nodes in red, and only corresponds_to edges in blue")
    args = parser.parse_args()

    ensure_dir(args.outdir)
    g = load_graph(args.graph)

    signals = [s.strip() for s in args.signals.split(",")] if args.signals else []
    seeds = find_seed_nodes(g, signals)
    if args.full_graph:
        sub = g.copy()
    else:
        sub = multi_ego_subgraph(g, seeds, args.hops) if seeds else g.copy()
        sub = trim_max_nodes(sub, args.max_nodes)

    # Save subgraph exports
    sub_graphml = os.path.join(args.outdir, "paper_subgraph.graphml")
    sub_gexf = os.path.join(args.outdir, "paper_subgraph.gexf")
    nx.write_graphml(sub, sub_graphml)
    nx.write_gexf(sub, sub_gexf)

    # Save figures
    out_png = os.path.join(args.outdir, "paper_kg.png")
    out_svg = os.path.join(args.outdir, "paper_kg.svg")
    out_pdf = os.path.join(args.outdir, "paper_kg.pdf")
    draw_graph(
        sub,
        args.title,
        out_png,
        out_svg,
        out_pdf,
        fig_width=args.fig_width,
        fig_height=args.fig_height,
        node_label_font_size=args.node_label_font_size,
        edge_label_font_size=args.edge_label_font_size,
        dpi=args.dpi,
        layout=args.layout,
        graphviz_prog=args.graphviz_prog,
        seed=args.seed,
        show_node_type_in_label=not args.hide_node_type_in_label,
        edge_alpha=args.edge_alpha,
        edge_width_scale=args.edge_width_scale,
        rtl_spec_corresponds_view=args.rtl_spec_corresponds_view,
    )

    # Save stats
    stats = {
        "source_graph": args.graph,
        "seed_queries": signals,
        "seed_nodes_found": len(seeds),
        "subgraph_stats": graph_stats(sub),
        "full_graph_stats": graph_stats(g),
    "corresponds_edge_count_in_source": sum(1 for _, _, a in g.edges(data=True) if is_corresponds_edge(a)),
        "legend": {
            "node_colors": {
                "rtl": "blue",
                "spec": "gray",
                "other": "teal",
            },
            "edge_colors": {
                "alignment(corresponds_to)": "red",
                "rtl_struct": "blue",
                "spec_rel": "gray",
                "other": "lightgray",
            },
        },
    }
    with open(os.path.join(args.outdir, "paper_kg_stats.json"), "w") as f:
        json.dump(stats, f, indent=2)

    print(f"[OK] Figure: {out_png}")
    print(f"[OK] Figure: {out_svg}")
    print(f"[OK] Figure: {out_pdf}")
    print(f"[OK] Subgraph: {sub_graphml}")
    print(f"[OK] Subgraph: {sub_gexf}")
    print(f"[OK] Stats: {os.path.join(args.outdir, 'paper_kg_stats.json')}")


if __name__ == "__main__":
    main()